Repository Tavonput/RealTimeRayTracing, pull requests merged in 2024-03, with the labels that each got.

#62 Multi-Pass Rendering
  RayTrace/Src/Application/application.cpp
  RayTrace/Src/Application/application.h
  RayTrace/Src/Application/entry.cpp
  RayTrace/Src/Application/model.cpp
  RayTrace/Src/Application/model.h
  RayTrace/Src/Core/buffer.cpp
  RayTrace/Src/Core/buffer.h
  RayTrace/Src/Core/depth_buffer.cpp
  RayTrace/Src/Core/depth_buffer.h
  RayTrace/Src/Core/descriptor.cpp
  RayTrace/Src/Core/descriptor.h
  RayTrace/Src/Core/framebuffer.cpp
  RayTrace/Src/Core/framebuffer.h
  RayTrace/Src/Core/image.cpp
  RayTrace/Src/Core/image.h
  RayTrace/Src/Core/pipeline.cpp
  RayTrace/Src/Core/pipeline.h
  RayTrace/Src/Core/render_pass.cpp
  RayTrace/Src/Core/render_pass.h
  RayTrace/Src/Core/renderer.cpp
  RayTrace/Src/Core/renderer.h
  RayTrace/Src/Core/swapchain.cpp
  RayTrace/Src/Core/swapchain.h
  RayTrace/Src/Core/texture.cpp
  RayTrace/Src/Core/texture.h
  RayTrace/Src/Cpu-Raytracing/cpu_raytracer.cpp
  RayTrace/Src/Cpu-Raytracing/cpu_raytracer.h
  RayTrace/Src/Scene/cornell_box.cpp
  RayTrace/Src/Scene/simple_cube_scene.cpp
  RayTrace/Src/Shaders/lighting.frag
  RayTrace/Src/Shaders/post.frag
  RayTrace/Src/Shaders/post.vert
  RayTrace/Src/Utils/stb_image_usage.cpp
  RayTrace/Src/Utils/stb_image_usage.h
  Scripts/compile_shaders.py
  Vendor/stbimage/LICENSE.txt
  Vendor/stbimage/stb_image.h
  Vendor/stbimage/stb_image_write.h
  premake5.lua
Labels: enhancement

#63 Add unit testing
  RayTrace/Src/Core/descriptor.cpp
  Tests/Src/test_application.cpp
  Tests/Src/test_core.cpp
  Tests/Src/test_header.h
  premake5.lua
Labels: enhancement

#68 touch up on dark mode and nav-bar
  Raytracing_wesbite/image/moon.png
  Raytracing_wesbite/image/sun.png
  Raytracing_wesbite/index.html
  Raytracing_wesbite/script.js
  Raytracing_wesbite/styles.css
Labels: documentation, enhancement

#74 Competed website
  Raytracing_wesbite/image/back.png
  Raytracing_wesbite/image/ex.png
  Raytracing_wesbite/image/raytracing.png
  Raytracing_wesbite/index.html
  Raytracing_wesbite/script.js
  Raytracing_wesbite/styles.css
Labels: bug, enhancement

#79 locking UI
  RayTrace/Src/Application/Gui.cpp
  RayTrace/Src/Application/entry.cpp
Labels: enhancement
